gff: GCF_000001405.25_GRCh37.p13_genomic.gtf 
output_format: gtf
original_chroms: original_chroms.txt
new_chroms: new_chroms.txt
original_fasta: GCF_000001405.25_GRCh37.p13_genomic.fna  
new_fasta: GRCh38.fa 
word_size: 50 
